name: On pull request

on:
    push:
        branches:
            - main
jobs:
    plan:
        name: Plan terraform
        uses: ./.github/workflows/review.yml

    apply:
        name: 'Terragrunt'
        needs: plan
        runs-on: 'self-hosted'
        environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    
        steps:
            - name: 'Terragrunt Apply'
              run: cd "${GITHUB_WORKSPACE}/environments/development" && terragrunt run-all apply --non-interactive
              shell: bash